### ISSUE TITLE
lib breaks the web version 

### ISSUE THREAD

**Issue by aleksandarbos** [netguru/sticky-parallax-header#406]
### Environment

Library version: `^1.0.0-rc.9`
OS version: web

expo v48 sdk

### Affected platforms

- [ ] Android
- [ ] iOS

### Current behavior

when starting web app:

```
DevTools failed to load source map: Could not load content for chrome-extension://gighmmpiobklfepjocnamgkkbiglidom/browser-polyfill.js.map: System error: net::ERR_FILE_NOT_FOUND
browser.js:38 Uncaught Invariant Violation: `createAnimatedComponent` does not support stateless functional components; use a class component instead.
    at invariant (http://localhost:19006/static/js/bundle.js:165861:15)
    at Module.createAnimatedComponent (http://localhost:19006/static/js/bundle.js:67725:51)
    at ./node_modules/react-native-sticky-parallax-header/lib/module/predefinedComponents/AvatarHeader/components/HeaderBar.js (http://localhost:19006/static/js/bundle.js:90845:91)
    at __webpack_require__ (http://localhost:19006/static/js/bundle.js:288272:33)
    at fn (http://localhost:19006/static/js/bundle.js:288488:21)
    at ./node_modules/react-native-sticky-parallax-header/lib/module/predefinedComponents/AvatarHeader/AvatarHeaderFlatList.js (http://localhost:19006/static/js/bundle.js:90382:79)
    at __webpack_require__ (http://localhost:19006/static/js/bundle.js:288272:33)
    at fn (http://localhost:19006/static/js/bundle.js:288488:21)
    at ./node_modules/react-native-sticky-parallax-header/lib/module/index.js (http://localhost:19006/static/js/bundle.js:90322:113)
    at __webpack_require__ (http://localhost:19006/static/js/bundle.js:288272:33)
invariant @ browser.js:38
createAnimatedComponent @ createAnimatedComponent.js:82
./node_modules/react-native-sticky-parallax-header/lib/module/predefinedComponents/AvatarHeader/components/HeaderBar.js @ HeaderBar.tsx:33
__webpack_require__ @ bootstrap:24
fn @ hot module replacement:62
./node_modules/react-native-sticky-parallax-header/lib/module/predefinedComponents/AvatarHeader/AvatarHeaderFlatList.js @ index.tsx:29
__webpack_require__ @ bootstrap:24
fn @ hot module replacement:62
./node_modules/react-native-sticky-parallax-header/lib/module/index.js @ useResponsiveSize.ts:15
__webpack_require__ @ bootstrap:24
fn @ hot module replacement:62
./src/components/parts/Journey.tsx @ GratitudeJar.js:75
__webpack_require__ @ bootstrap:24
fn @ hot module replacement:62
./src/components/screens/JourneyScreen.tsx @ HomeScreen.tsx:214
__webpack_require__ @ bootstrap:24
fn @ hot module replacement:62
./src/navigation/TabNavigator.js @ StackNavigator.js:184
__webpack_require__ @ bootstrap:24
fn @ hot module replacement:62
./src/navigation/StackNavigator.js @ BottomNavigationBar.tsx:113
__webpack_require__ @ bootstrap:24
fn @ hot module replacement:62
./src/navigation/index.js @ TabNavigator.js:66
__webpack_require__ @ bootstrap:24
fn @ hot module replacement:62
./App.js @ time.svg:36
__webpack_require__ @ bootstrap:24
fn @ hot module replacement:62
./index.js @ App.js:41
__webpack_require__ @ bootstrap:24
(anonymous) @ startup:6
(anonymous) @ startup:6
```

### Expected behavior

shoudln't

### Reproduction

install library and start web via expo managed rn app

**Comment by aleksandarbos** [comment]
duplicate of https://github.com/netguru/sticky-parallax-header/issues/379, solved in: https://github.com/netguru/sticky-parallax-header/issues/379#issuecomment-1544153006
